server:
  port: 8080
spring:
#  config:
#    import: env.properties
  mail:
    host: live.smtp.mailtrap.io
    port: 2525
    username: api
    password: ${MAILPASSWORD:fail}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: wordle
---
#spring:
#  jpa:
#    open-in-view: false
#    hibernate:
#      #      ddl-auto: update
#      ddl-auto: create-drop
#      dialect: org.hibernate.dialect.SQLServer2012Dialect
#    show-sql: false
#  datasource:
#    url: ${PRODDBURL:fail}
#    username: ${PRODDBUSERNAME:fail}
#    password: ${PRODDBPASSWORD:fail}
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
---
sample-greeting: ${SAMPLEGREETING:Hello there!}
url: ${PRODDBURL:fail}
db-username: ${PRODDBUSERNAME:fail}
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true