server:
  port: 8081
spring:
#  config:
#    import: env.properties
  mail:
    host: live.smtp.mailtrap.io
    port: 2525
    username: api
    password: ${MAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    open-in-view: false
    hibernate:
      #      ddl-auto: update
      ddl-auto: create-drop
      show-sql: false
      dialect: org.hibernate.dialect.SQLServer2012Dialect
---
spring:
  datasource:
    url: ${PRODDBURL}
    username: ${PRODDBUSERNAME}
    password: ${PRODDBPASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
---
sample-greeting: ${SAMPLEGREETING:Hello there!}
sample-url: ${PRODDBURL:fail}
sample-username: ${PRODDBUSERNAME:fail}
---
#spring:
#  datasource:
##    url: jdbc:h2:mem:testdb
#    url: ${PRODDBURL}
#    driverClassName: org.h2.Driver
##    username: sa
#    username: ${PRODDBUSERNAME}
##    password:
#    password: ${PRODDBPASSWORD}
#  h2:
#    console:
#      enabled: true