server:
  port: 8081
spring:
#  config:
#    import: env.properties
  mail:
    host: live.smtp.mailtrap.io
    port: 2525
    username: api
    password: ${MAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    open-in-view: false
    hibernate:
      #      ddl-auto: update
      ddl-auto: create-drop
      show-sql: false
      dialect: org.hibernate.dialect.SQLServer2012Dialect
---
spring:
  datasource:
    url: ${PRODDBURL}
    username: ${PRODDBUSERNAME}
    password: ${PRODDBPASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver