server:
  port: 8080
spring:
  config:
    import: env.properties
  mail:
    host: live.smtp.mailtrap.io
    port: 2525
    username: api
    password: ${MAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: wordle
  jpa:
    open-in-view: false
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
  datasource:
    url: ${PRODDBURL}
    username: ${PRODDBUSERNAME}
    password: ${PRODDBPASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver